-- MySQL Script generated by MySQL Workbench
-- Mon Jun  2 10:38:19 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Mario_mundo_senai
-- -----------------------------------------------------
SELECT * FROM player;
-- -----------------------------------------------------
-- Schema Mario_mundo_senai
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Mario_mundo_senai` DEFAULT CHARACTER SET utf8 ;
USE `Mario_mundo_senai` ;

-- -----------------------------------------------------
-- Table `Mario_mundo_senai`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mario_mundo_senai`.`player` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Mario_mundo_senai`.`pontuacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Mario_mundo_senai`.`pontuacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pontos` INT NOT NULL,
  `player_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `player_id_idx` (`player_id` ASC) VISIBLE,
  CONSTRAINT `player_id`
    FOREIGN KEY (`player_id`)
    REFERENCES `Mario_mundo_senai`.`player` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
